### ISSUE TITLE
Snap unable to install

### ISSUE THREAD

**Issue by zmraul** [canonical/snap-mysqld-exporter#4]
## Steps to reproduce
1. `snap install mysqld-exporter --channel edge`

## Expected behavior

Snap installs normally.

## Actual behavior
Following error shows up:
```shell
$ snap install mysqld-exporter --channel="edge"                                                                                                                               
error: cannot perform the following tasks:                                                                                          
- Run install hook of "mysqld-exporter" snap if present (run hook "install": /snap/mysqld-exporter/6/snap/hooks/install: 9: exec: /s
nap/mysqld-exporter/6/bin/snap-helpers-hook: not found)                                                                             
```

**Comment by taurus-forever** [comment]
Hi @wolsen , I think you have some hidden automated published somewhere :-D
Can it be disabled or at least tell us how to use it. CC: @jardon please talk to Billy and learn about snap auto-publisher here.
Tnx!

**Comment by wolsen** [comment]
> Hi @wolsen , I think you have some hidden automated publisher somewhere :-D Can it be disabled or at least tell us how to use it. CC: @jardon please talk to Billy and learn about snap auto-publisher here. Tnx!

Hi @taurus-forever, the repo is linked to the snapstore and it will automatically build and publish new versions when patches are landed in master (reference the [build from github docs](https://snapcraft.io/docs/build-from-github) on the snapcraft documentation.

One advantage is that this allows the snap to build and publish across all architectures because it uses the launchpad builders to build and publish. One disadvantage is that we're primarily running the tests on an amd64 machine and calling it good for publishing, which leaves open the risk that it doesn't work correctly on an alternate architecture.

This should be revisited in the future, but for now it works okay enough.
